--[[
CheaterEvents.lua
all Events consts
--]]

CHEAT_BUTTON_CLICKED_EVENT = "CHEAT_BUTTON_CLICKED"
THREE_FINGERS_PRESSED_EVENT = "THREE_FINGERS_PRESSED"
CHEAT_CATEGORY_CLICKED_EVENT = "CHEAT_CATEGORY_CLICKED"
CHEAT_X_BUTTON_CLICKED_EVENT = "CHEAT_X_BUTTON_CLICKED"
LUA_ALERT_DISMISSED_EVENT = "LUA_ALERT_DISMISSED"
